---
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: us-east-1a
      ImageId: ami-0b72821e2f351e396
      KeyName: vilasnv2
      