---
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: us-east-1b
      ImageId: ami-0dbc3d7bc646e8516
      KeyName: bitsnvirginia