---
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      AvailabilityZone: us-east-2b
      ImageId: ami-0d406e26e5ad4de53
      KeyName: vilasohio