# Install maven and java and execute mvn clean package before doing this 
FROM openjdk:11-jre-slim
COPY target/rating-0.0.1-SNAPSHOT.jar /usr/local/lib/demo.jar
EXPOSE 8082
ENTRYPOINT ["java","-jar","/usr/local/lib/demo.jar"]




#
# Build stage
#
#FROM maven:3.6.0-jdk-11-slim AS build
#COPY . .
#RUN mvn clean package

#
# Package stage



# Install maven and java and execute mvn clean package before doing this 
#FROM openjdk:11-jre-slim
#COPY --from=build target/rating-0.0.1-SNAPSHOT.jar /usr/local/lib/demo.jar
#COPY target/rating-0.0.1-SNAPSHOT.jar /usr/local/lib/demo.jar
#EXPOSE 8082
#ENTRYPOINT ["java","-jar","/usr/local/lib/demo.jar"]